# Generated by Django 3.1.4 on 2021-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseIMG', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
